# -*- coding: utf-8 -*-
"""T1 – Atividade de Aprofundamento - Leonado Nunes Cerqueira

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGTIExkd7-AX0UxWvVEdX4IHqqtwYtAx
"""

import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

df_copa = pd.read_csv("/content/sample_data/Copa_do_mundo.txt", sep='\n').rename(columns = {'Copa do Mundo FIFA':'Copa_do_Mundo'})

texto = []
  
for index, texto_linha in df_copa.iterrows():

    texto_linha = texto_linha.Copa_do_Mundo
      
    texto.append(texto_linha)
  
for i in range(len(texto)):
    texto[i] = texto[i].lower() 
    texto[i] = texto[i].replace('\n','')
    texto[i] = texto[i].replace('.','')
    texto[i] = texto[i].replace(',','')
    texto[i] = texto[i].replace('(','')
    texto[i] = texto[i].replace(')','')
    texto[i] = texto[i].replace('?','')
    texto[i] = texto[i].replace('\'','')

mydict = {}                             

for line in texto:

  line = line.lower()                  
  words = line.split()                  
  for word in words:                      
    if word not in mydict.keys():         
      mydict[word] = 1                    
    else:                                  
      mydict[word] =  mydict[word] + 1

base_palavras = pd.DataFrame(mydict.items(),  columns=['PALAVRA', 'CONTAGEM']).sort_values('CONTAGEM',ascending=False)
base_palavras = base_palavras[base_palavras['CONTAGEM'] > 5] 


plt.figure(figsize=(20,8))
mpl.style.use(['seaborn'])
sns.barplot(x=base_palavras.PALAVRA,y=base_palavras['CONTAGEM'])
plt.xticks(rotation=90) 

plt.show()

base_palavras_nova = pd.DataFrame(mydict.items(),  columns=['PALAVRA', 'CONTAGEM']).sort_values('CONTAGEM',ascending=False)
base_palavras_nova = base_palavras_nova[base_palavras_nova['CONTAGEM'] > 5] 

lista_retirar = ['de','a','o','em','e',
                 'do','da','que','com',
                 'na','para','é','foi',
                 'um','no','mais','uma',
                 'os','por','as','como',
                 'nas','se','pela','das',
                 'à','ao','são','foram',
                 'aos','nos','sua','ter',
                 'já','desde','até','ou',
                 'ser','também','não']

base_palavras_nova = base_palavras_nova[~base_palavras_nova['PALAVRA'].isin(lista_retirar)]



plt.figure(figsize=(20,8))
mpl.style.use(['seaborn'])
sns.barplot(x=base_palavras_nova.PALAVRA,y=base_palavras_nova['CONTAGEM'])
plt.xticks(rotation=90) 

plt.show()


# apoio para printar as palavras para retirar
## col_list = base_palavras_nova.PALAVRA.values.tolist()
## print(col_list)

"""## **Conclusão**

**Texto escolhido**: Como estamos em época de Copa, decidi escolher esse tema. Retirei o texto no link > https://pt.wikipedia.org/wiki/Copa_do_Mundo_FIFA .

Retirei as informações manualmente e colei no TXT que tambem segue importado ("Copa_do_mundo.txt")

**Analise**: Conforme esperado, as preposições e palavras que servem de "apoio", como alguns verbos, aparecem mais vezes no texto (conforme primeiro grafico). Entao, no segundo grafico extrai da base as palavras que considero irrelevantes para a analise (lista > *lista_retirar*). No segundo grafico, já é possivel localizar algumas palavras chaves, como "Brasil" e "cinco" (levantando a hipotese de se tratar do brasil ser o unico pentacampeao), assim como "alemanha e uruguai" (seleções que ja cediaram copa e foram campeoes mais de 1x)
"""